<?php

/*********************************************************************
* Extension configuration file for ext "lp_access".
*
* Generated by ext 05-08-2013 21:04 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Access Hours',
  'description' => 'Extend the access tab with a selection of online hours in content elements. Doc: http://docs.typo3.org/typo3cms/extensions/lp_access/ and Git: https://github.com/lars85/TYPO3-Extensions-lp_access/',
  'category' => 'be',
  'shy' => 0,
  'version' => '1.0.2',
  'dependencies' => '',
  'conflicts' => '',
  'priority' => '',
  'loadOrder' => '',
  'module' => '',
  'state' => 'stable',
  'uploadfolder' => 0,
  'createDirs' => '',
  'modify_tables' => '',
  'clearcacheonload' => 0,
  'lockType' => '',
  'author' => 'Lars Peipmann',
  'author_email' => 'Lars@Peipmann.de',
  'author_company' => '',
  'CGLcompliance' => NULL,
  'CGLcompliance_note' => NULL,
  'constraints' => 
  array (
    'depends' => 
    array (
      'typo3' => '6.0.0-6.1.99',
    ),
    'conflicts' => 
    array (
    ),
    'suggests' => 
    array (
    ),
  ),
  'suggests' => 
  array (
  ),
  'user' => 'lars85',
  'comment' => 'Solves problem with directmail',
);
